services:
  - type: web
    name: valentine-web
    runtime: python
    buildCommand: ""
    startCommand: gunicorn app:app
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
